version: "3.9"

services:
  ghost:
    image: ghost:5.38.0-alpine
    container_name: ghost
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - db
      - contact-svc
    volumes:
      - "$PWD/sccc-content:/var/lib/ghost/content/"
    environment:
      url: https://www.suttonchallengers.org
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      mail__transport: SMTP
      mail__options__service: ${EMAIL_SERVICE}
      mail__options__secure: true
      mail__options__auth__user: ${EMAIL_USER}
      mail__options__auth__pass: ${EMAIL_PASSWORD}
      mail__from: ${EMAIL_FROM}

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    volumes:
      - "$PWD/sccc-mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  contact-svc:
    image: vaibhz/sccc-contact-service
    container_name: sccc-contact-service
    restart: always
    ports:
      - 7000:7000
    environment:
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      mail__options__secure: true
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      TRUNSTILE_SECRET_KEY: ${TRUNSTILE_SECRET_KEY}

  play-cricket-api:
    image: vaibhz/sccc-pc-api
    container_name: sccc-pc-api
    restart: always
    ports:
      - 9090:9090

  sccc-teams-api:
    image: vaibhz/sccc-teams-service
    container_name: sccc-teams-service
    restart: always
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./sccc-gcp-179141288987.json
        target: usr/src/app//sccc-gcp-179141288987.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GCLOUD_PROJECT: ${GCLOUD_PROJECT}
