name: SCCC Website deployer

on:
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-copy-deployment-artifacts:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build deployment artifacts
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.x'
      - name: Install npm dependencies, test and zip theme
        run: |
          cd sccc-theme
          npm install
          npm run test:ci
          npm run zip
      - name: Copy artifacts to Server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.REMOTE_TARGET }}
          rm: true
          overwrite: true

  deploy-artifacts:
   runs-on: ubuntu-latest
   needs: [build-and-copy-deployment-artifacts]
   steps:
     - name: Deploy artifacts
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.REMOTE_HOST }}
         username: ${{ secrets.REMOTE_USER }}
         key: ${{ secrets.SERVER_SSH_KEY }}
         source: ${{ secrets.SOURCE }}
         script: |
           cd ${{ secrets.REMOTE_TARGET }}
           unzip sccc-theme/dist/sccc-theme.zip -d sccc-theme/
           rm -r sccc-theme/dist
           docker-compose -f stack.yml down
           docker system prune -f
           docker-compose -f stack.yml up -d
