name: SCCC Website deployer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deployment-artifacts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build deployment artifacts
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14.x'          
      - name: Install npm dependencies, test and zip theme
        run: cd sccc-theme && npm install && npm run test:ci && npm run zip

  copy-deployment-artifacts:
    runs-on: ubuntu-latest
    needs: [build-deployment-artifacts]
    steps:
      - name: Copy artifacts to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.REMOTE_TARGET }}
          rm: true
          overwrite: true          

  deploy-artifacts:
   runs-on: ubuntu-latest
   needs: [copy-deployment-artifacts]
   steps:
     - name: Deploy artifacts
       uses: actions/github-script@v6
       with:
         script: |
           unzip ${{ secrets.REMOTE_TARGET }}/sccc-theme/dist/sccc-theme.zip -d sccc-theme/
           rm -r sccc-theme/dist
           docker-compose -f stack.yml up -d
