name: SCCC Website deployer

on:
  push:
    branches: main
  pull_request:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-copy-deployment-artifacts:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build deployment artifacts
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.x'
      - name: Install npm dependencies, test and zip theme
        run: |
          apt-get update && apt-get upgrade && apt-get install zip -y
          zip -r sccc-content.zip sccc-content -x sccc-content/data/**\* sccc-content/themes/**\* sccc-content/logs/**\*
          cd sccc-content/themes/sccc-theme
          npm install
          npm run test:ci
          npm run zip
      - name: Copy artifacts to Server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "sccc-content.zip,sccc-content/themes/sccc-theme/dist/sccc-theme.zip,stack.yml"
          target: ${{ secrets.REMOTE_TARGET }}/new_deploy/
          rm: true

  deploy-artifacts:
   runs-on: ubuntu-latest
   needs: [build-and-copy-deployment-artifacts]
   steps:
     - name: Deploy artifacts
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.REMOTE_HOST }}
         username: ${{ secrets.REMOTE_USER }}
         passphrase: ${{ secrets.PASSWORD }}
         key: ${{ secrets.SERVER_SSH_KEY }}
         script: |
           cd ${{ secrets.REMOTE_TARGET }}
           docker compose -f stack.yml down
           docker system prune -af
           mkdir -p backup_logs
           cp -r sccc-content/logs/* backup_logs/.
           rm -rf sccc-content stack.yml
           unzip ${{ secrets.REMOTE_TARGET }}/new_deploy/sccc-content.zip
           unzip -o ${{ secrets.REMOTE_TARGET }}/new_deploy/sccc-content/themes/sccc-theme/dist/sccc-theme.zip -d ${{ secrets.REMOTE_TARGET }}/sccc-content/themes/sccc-theme
           cp ${{ secrets.REMOTE_TARGET }}/new_deploy/stack.yml .
           docker compose -f stack.yml up -d
